# Generated by Django 4.2.6 on 2023-10-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geniusvoice', '0005_user_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
